from logging.config import fileConfig

from sqlalchemy import create_engine, pool
from sqlalchemy.types import TypeEngine

from alembic import context
import advanced_alchemy.types  # noqa: F401 — needed for autogenerated migrations
from advanced_alchemy.base import UUIDBase
from advanced_alchemy.types import GUID

# Import all models so Alembic can detect them
from app.lib.crud.discovery import discover_models
from app.lib.settings import get_settings

discover_models()

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = UUIDBase.metadata

# Derive a sync URL from the DATABASE_URL env var.
# Alembic runs synchronously, so async drivers (aiosqlite, asyncpg) must be
# replaced with their sync equivalents.
settings = get_settings()
_sync_url = settings.database_url.replace("+aiosqlite", "").replace(
    "+asyncpg", "+psycopg2"
)


def _compare_type(
    _ctx: object,
    _inspected_column: object,
    _metadata_column: object,
    inspected_type: TypeEngine,
    metadata_type: TypeEngine,
) -> bool | None:
    """Ignore spurious GUID vs NUMERIC diffs on SQLite."""
    if isinstance(metadata_type, GUID):
        return False
    return None


def run_migrations_offline() -> None:
    context.configure(
        url=_sync_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=_compare_type,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(_sync_url, poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
            compare_type=_compare_type,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
